import 'dart:async';
import 'package:flutter/material.dart';
import 'dashboard_screen.dart';

class SplashScreen extends StatefulWidget {
  const SplashScreen({super.key});

  @override
  _SplashScreenState createState() => _SplashScreenState();
}

class _SplashScreenState extends State<SplashScreen> {
  @override
  void initState() {
    super.initState();

    Timer(const Duration(seconds: 3), () {
      Navigator.of(context).pushReplacement(
        MaterialPageRoute(builder: (context) => const DashboardScreen()),
      );
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: Center(
        child: Image.asset(
          'assets/images/kisan_logo.png',
          width: 200,
          height: 200,
        ),
      ),
    );
  }
}
// import 'package:flutter/material.dart';
//
// void main() {
//   runApp(const FigmaToCodeApp());
// }
//
// // Generated by: https://www.figma.com/community/plugin/842128343887142055/
// class FigmaToCodeApp extends StatelessWidget {
//   const FigmaToCodeApp({super.key});
//
//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       theme: ThemeData.dark().copyWith(
//         scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
//       ),
//       home: Scaffold(
//         body: ListView(children: [
//           ProfilePageType(),
//         ]),
//       ),
//     );
//   }
// }
//
// class ProfilePageType extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return Column(
//       children: [
//         Container(
//           width: 393,
//           height: 852,
//           clipBehavior: Clip.antiAlias,
//           decoration: BoxDecoration(color: const Color(0xFFFFF7A2)),
//           child: Stack(
//             children: [
//               Positioned(
//                 left: 253.01,
//                 top: -305,
//                 child: Container(
//                   transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(0.70),
//                   width: 898.66,
//                   height: 1098.36,
//                   decoration: ShapeDecoration(
//                     gradient: LinearGradient(
//                       begin: Alignment(0.52, 0.26),
//                       end: Alignment(0.63, 0.67),
//                       colors: [const Color(0xFFFECC6D), const Color(0x99E7C9AC)],
//                     ),
//                     shape: RoundedRectangleBorder(
//                       borderRadius: BorderRadius.only(bottomRight: Radius.circular(500)),
//                     ),
//                     shadows: [
//                       BoxShadow(
//                         color: Color(0x3F000000),
//                         blurRadius: 4,
//                         offset: Offset(0, 4),
//                         spreadRadius: 0,
//                       )
//                     ],
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: -12,
//                 top: 0,
//                 child: Container(
//                   width: 414,
//                   height: 44,
//                   clipBehavior: Clip.antiAlias,
//                   decoration: BoxDecoration(),
//                   child: Stack(
//                     children: [
//                       Positioned(
//                         left: 360,
//                         top: 18,
//                         child: Container(
//                           width: 26.60,
//                           height: 12.50,
//                           child: Stack(),
//                         ),
//                       ),
//                       Positioned(
//                         left: 39,
//                         top: 16,
//                         child: Text(
//                           '19:02',
//                           textAlign: TextAlign.center,
//                           style: TextStyle(
//                             color: Colors.black /* Light-Ink */,
//                             fontSize: 18,
//                             fontFamily: 'SF Pro Display',
//                             fontWeight: FontWeight.w600,
//                             height: 1,
//                             letterSpacing: -0.36,
//                           ),
//                         ),
//                       ),
//                     ],
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 119,
//                 top: 198,
//                 child: Container(
//                   width: 155,
//                   height: 155,
//                   decoration: BoxDecoration(
//                     image: DecorationImage(
//                       image: NetworkImage("https://placehold.co/155x155"),
//                       fit: BoxFit.cover,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 147,
//                 top: 372,
//                 child: Text(
//                   'User',
//                   textAlign: TextAlign.center,
//                   style: TextStyle(
//                     color: Colors.black,
//                     fontSize: 30,
//                     fontFamily: 'Karla',
//                     fontWeight: FontWeight.w700,
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 226,
//                 top: 380,
//                 child: Container(
//                   width: 20,
//                   height: 20,
//                   decoration: BoxDecoration(
//                     image: DecorationImage(
//                       image: NetworkImage("https://placehold.co/20x20"),
//                       fit: BoxFit.cover,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 118,
//                 top: 415,
//                 child: Text(
//                   'user1234@gmail.com',
//                   textAlign: TextAlign.center,
//                   style: TextStyle(
//                     color: Colors.black,
//                     fontSize: 16,
//                     fontFamily: 'Karla',
//                     fontWeight: FontWeight.w400,
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 13,
//                 top: 506,
//                 child: Text(
//                   'Type     :',
//                   textAlign: TextAlign.center,
//                   style: TextStyle(
//                     color: Colors.black,
//                     fontSize: 20,
//                     fontFamily: 'Karla',
//                     fontWeight: FontWeight.w400,
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 115,
//                 top: 506,
//                 child: Container(
//                   width: 83,
//                   height: 23,
//                   decoration: BoxDecoration(color: const Color(0xFFF7F7F7)),
//                 ),
//               ),
//               Positioned(
//                 left: 110,
//                 top: 508,
//                 child: SizedBox(
//                   width: 69,
//                   height: 17,
//                   child: Text(
//                     'Grocery',
//                     textAlign: TextAlign.center,
//                     style: TextStyle(
//                       color: Colors.black,
//                       fontSize: 15,
//                       fontFamily: 'Karla',
//                       fontWeight: FontWeight.w500,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 176,
//                 top: 508,
//                 child: Container(
//                   width: 18,
//                   height: 18,
//                   decoration: BoxDecoration(
//                     image: DecorationImage(
//                       image: NetworkImage("https://placehold.co/18x18"),
//                       fit: BoxFit.cover,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 120,
//                 top: 681,
//                 child: SizedBox(
//                   width: 122,
//                   height: 41,
//                   child: Text(
//                     'Logout',
//                     textAlign: TextAlign.center,
//                     style: TextStyle(
//                       color: const Color(0xFFFF0000),
//                       fontSize: 36,
//                       fontFamily: 'Karla',
//                       fontWeight: FontWeight.w700,
//                       textDecoration: TextDecoration.underline,
//                       shadows: [Shadow(offset: Offset(0, 4), blurRadius: 4, color: Color(0xFF000000).withOpacity(0.25))],
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 244,
//                 top: 690,
//                 child: Container(
//                   width: 30,
//                   height: 30,
//                   decoration: BoxDecoration(
//                     image: DecorationImage(
//                       image: NetworkImage("https://placehold.co/30x30"),
//                       fit: BoxFit.cover,
//                     ),
//                     boxShadow: [
//                       BoxShadow(
//                         color: Color(0x3F000000),
//                         blurRadius: 4,
//                         offset: Offset(0, 4),
//                         spreadRadius: 0,
//                       )
//                     ],
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 151,
//                 top: 63,
//                 child: Container(
//                   width: 92,
//                   height: 92,
//                   decoration: ShapeDecoration(
//                     image: DecorationImage(
//                       image: NetworkImage("https://placehold.co/92x92"),
//                       fit: BoxFit.cover,
//                     ),
//                     shape: OvalBorder(),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 0,
//                 top: 801,
//                 child: Container(
//                   width: 393,
//                   height: 51,
//                   decoration: BoxDecoration(color: const Color(0xFFFDC256)),
//                 ),
//               ),
//               Positioned(
//                 left: 184,
//                 top: 808,
//                 child: Container(
//                   width: 25,
//                   height: 25,
//                   decoration: BoxDecoration(
//                     image: DecorationImage(
//                       image: NetworkImage("https://placehold.co/25x25"),
//                       fit: BoxFit.cover,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 176,
//                 top: 834,
//                 child: SizedBox(
//                   width: 42,
//                   height: 11,
//                   child: Text(
//                     'Home',
//                     textAlign: TextAlign.center,
//                     style: TextStyle(
//                       color: Colors.black,
//                       fontSize: 9,
//                       fontFamily: 'SF Pro Rounded',
//                       fontWeight: FontWeight.w500,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 332,
//                 top: 803,
//                 child: Container(
//                   width: 47,
//                   height: 47,
//                   decoration: ShapeDecoration(
//                     color: const Color(0xFFF1DBA8),
//                     shape: OvalBorder(),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 343,
//                 top: 808,
//                 child: Container(
//                   width: 25,
//                   height: 25,
//                   decoration: BoxDecoration(
//                     image: DecorationImage(
//                       image: NetworkImage("https://placehold.co/25x25"),
//                       fit: BoxFit.cover,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 334,
//                 top: 834,
//                 child: SizedBox(
//                   width: 42,
//                   height: 11,
//                   child: Text(
//                     'User',
//                     textAlign: TextAlign.center,
//                     style: TextStyle(
//                       color: Colors.black,
//                       fontSize: 9,
//                       fontFamily: 'SF Pro Rounded',
//                       fontWeight: FontWeight.w500,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 264,
//                 top: 808,
//                 child: Container(
//                   width: 25,
//                   height: 25,
//                   decoration: BoxDecoration(
//                     image: DecorationImage(
//                       image: NetworkImage("https://placehold.co/25x25"),
//                       fit: BoxFit.cover,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 256,
//                 top: 834,
//                 child: SizedBox(
//                   width: 42,
//                   height: 11,
//                   child: Text(
//                     'History',
//                     textAlign: TextAlign.center,
//                     style: TextStyle(
//                       color: Colors.black,
//                       fontSize: 9,
//                       fontFamily: 'SF Pro Rounded',
//                       fontWeight: FontWeight.w500,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 104,
//                 top: 808,
//                 child: Container(
//                   width: 25,
//                   height: 25,
//                   decoration: BoxDecoration(
//                     image: DecorationImage(
//                       image: NetworkImage("https://placehold.co/25x25"),
//                       fit: BoxFit.cover,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 96,
//                 top: 834,
//                 child: SizedBox(
//                   width: 42,
//                   height: 11,
//                   child: Text(
//                     'Grocery',
//                     textAlign: TextAlign.center,
//                     style: TextStyle(
//                       color: Colors.black,
//                       fontSize: 9,
//                       fontFamily: 'SF Pro Rounded',
//                       fontWeight: FontWeight.w500,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 25,
//                 top: 808,
//                 child: Container(
//                   width: 25,
//                   height: 25,
//                   decoration: BoxDecoration(
//                     image: DecorationImage(
//                       image: NetworkImage("https://placehold.co/25x25"),
//                       fit: BoxFit.cover,
//                     ),
//                   ),
//                 ),
//               ),
//               Positioned(
//                 left: 17,
//                 top: 834,
//                 child: SizedBox(
//                   width: 42,
//                   height: 11,
//                   child: Text(
//                     'Farmer',
//                     textAlign: TextAlign.center,
//                     style: TextStyle(
//                       color: Colors.black,
//                       fontSize: 9,
//                       fontFamily: 'SF Pro Rounded',
//                       fontWeight: FontWeight.w500,
//                     ),
//                   ),
//                 ),
//               ),
//             ],
//           ),
//         ),
//       ],
//     );
//   }
// }

// import 'dart:async';
// import 'package:flutter/material.dart';
//
// void main() {
//   runApp(const MyApp());
// }
//
// /// Main app widget, with routes for splash and home screens
// class MyApp extends StatelessWidget {
//   const MyApp({super.key});
//
//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       title: 'Kisan Grocery Plus',
//       debugShowCheckedModeBanner: false,
//       theme: ThemeData(
//         primarySwatch: Colors.orange,
//       ),
//       initialRoute: '/',
//       routes: {
//         '/': (context) => const SplashScreen(),
//         '/home': (context) => const HomeScreen(),
//         // Add other routes here (login, profile, etc.)
//       },
//     );
//   }
// }
//
// /// Splash screen with timer navigation
// class SplashScreen extends StatefulWidget {
//   const SplashScreen({super.key});
//
//   @override
//   State<SplashScreen> createState() => _SplashScreenState();
// }
//
// class _SplashScreenState extends State<SplashScreen> {
//   @override
//   void initState() {
//     super.initState();
//     Timer(const Duration(seconds: 3), () {
//       Navigator.of(context).pushReplacementNamed('/home');
//     });
//   }
//
//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       backgroundColor: const Color(0xFFFFF7A2),
//       body: Center(
//         child: Column(
//           mainAxisAlignment: MainAxisAlignment.center,
//           children: [
//             Container(
//               width: 150,
//               height: 150,
//               decoration: const BoxDecoration(
//                 shape: BoxShape.circle,
//                 image: DecorationImage(
//                   image: AssetImage('assets/images/splashimage.png'),
//                   fit: BoxFit.cover,
//                 ),
//               ),
//             ),
//             const SizedBox(height: 20),
//             Text(
//               'Kisan Grocery Plus',
//               style: TextStyle(
//                 fontSize: 30,
//                 fontWeight: FontWeight.bold,
//                 color: Colors.brown[700],
//               ),
//             )
//           ],
//         ),
//       ),
//     );
//   }
// }
//
// /// Simple home screen placeholder
// class HomeScreen extends StatelessWidget {
//   const HomeScreen({super.key});
//
//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       appBar: AppBar(
//         title: const Text('Home Screen'),
//       ),
//       body: const Center(
//         child: Text('Welcome to the Home Screen', style: TextStyle(fontSize: 24)),
//       ),
//     );
//   }
// }
